package Structure.Commands;

public enum OtherCommand {
    CONNECT_SUCCESS,
    CONNECT_ERROR,

    ACCESS_SUCCESS,
    ACCESS_ERROR,

    GROUP_LIST,
    GROUP_PRODUCT_LIST,

    GROUP_INSERT_SUCCESS,
    GROUP_INSERT_ERROR,
    GROUP_DELETE,

    PRODUCT_INSERT_SUCCESS,
    PRODUCT_INSERT_ERROR,
    PRODUCT_UPDATE_SUCCESS,
    PRODUCT_UPDATE_ERROR,
    PRODUCT_AMOUNT_ADD,
    PRODUCT_AMOUNT_REDUCE_SUCCESS,
    PRODUCT_AMOUNT_REDUCE_ERROR,
    PRODUCT_DELETE,
    PRODUCT_FIND_LIST,

    SHOP_UPDATE_LIST,

    CLOSE
}

