package Structure.Commands;

public enum UserCommand {
    CONNECT_REQUEST,
    ACCESS_REQUEST,

    GROUP_PRODUCT_LIST,
    GROUP_LIST,

    PRODUCT_FIND,
    PRODUCT_INSERT,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    PRODUCT_AMOUNT_ADD,

    GROUP_INSERT,
    GROUP_UPDATE,
    GROUP_DELETE,
}
